### ISSUE TITLE
Can't seem to download models from Drive

### ISSUE THREAD

**Issue by ghost** [camenduru/converter-colab#3]
Full output : https://hastebin.skyra.pw/mahuyuyape.bash

The URL i'm sharing is set to be viewed by everyone, is a direct link to the .ckpt file, can be downloaded by other people. Doesn't seem to work here for some reason.

**Comment by camenduru** [comment]
file is empty 😐

**Comment by ghost** [comment]
Here is a updated output : https://hastebin.skyra.pw/quwuciyuba.bash
Sorry for the issue, as it's not under my control when the service decides to delete their contents and i wanted to provide a easy way of letting people to view the log file. I can also upload them to other services such as 0x0 if requested. The issue also should be easy to reproduce since i tried it on two different browsers and got the same result.

**Comment by camenduru** [comment]
maybe fixed please try again
