### ISSUE TITLE
Ckpt -> diffusers upload error

### ISSUE THREAD

**Issue by mcgalleg** [camenduru/converter-colab#4]
Hello,
When I try to push the converted ckpt to hugging face, I'm getting the following error.  I know the access key is working because it creates the model space on hugging face. Would appreciate any insight into this one.  thx

ValueError: Provided path: 'pt' is not a directory

**Comment by camenduru** [comment]
is there any log looks like model not correctly converted also please try this https://huggingface.co/spaces/camenduru/converter maybe works

**Comment by mcgalleg** [comment]
Okay, I'll circle back on trying that.  Thank you.
