### ISSUE TITLE
Gradio Error

### ISSUE THREAD

**Issue by duskfallcrew** [camenduru/converter-colab#6]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-1-0afb8c951a40>](https://localhost:8080/#) in <module>
      5 import os, gdown, gc
      6 import numpy as np
----> 7 import gradio as gr
      8 from diffusers import FlaxStableDiffusionPipeline, StableDiffusionPipeline
      9 import torch

ModuleNotFoundError: No module named 'gradio'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by camenduru** [comment]
thanks @kieranxsomer ❤ please try again
